language: node.js
node_js:
  - 6
cashe:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@5.0.0
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master