language: node_js
node_js:
  - 6
cashe:
  directories:
    - "node_modules"
script:
  - npm test
  - npm run build
before_deploy:
  - ./custom_domain.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
    fqdn: showme.zapto.org