language: node.js
node_js:
  - 6
cashe:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@5.0.0
install:
  - npm install
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master